//
//  PredefinedColorTable.swift
//  Fouris
//  Adapted from BumpCamera and Visualizer Clock.
//
//  Created by Stuart Rankin on 8/31/19.
//  Copyright © 2018, 2019 Stuart Rankin. All rights reserved.
//

import Foundation
import UIKit

/// Holds an array of pre-defined, named colors.
class PredefinedColorTable
{
    /// List of pre-defined, named colors.
    public static var Colors: [PredefinedColor] =
        [
            //Japanese historic colors.
            PredefinedColor("One Lover", "一斤染", "Japanese", "#ffe6e0"),
            PredefinedColor("Peach", "桃色", "Japanese", "#f48386"),
            PredefinedColor("Azelea", "躑躅色", "Japanese", "#e73377"),
            PredefinedColor("Scarlet", "猩々緋", "Japanese", "#e1382e"),
            PredefinedColor("Cinnamon", "檜皮色", "Japanese", "#7b4334"),
            PredefinedColor("Azuki Bean", "小豆色", "Japanese", "#753733"),
            PredefinedColor("Plum", "紅梅色", "Japanese", "#f1939c"),
            PredefinedColor("Mudan", "牡丹色", "Japanese", "#cf4b8e"),
            PredefinedColor("Suyin", "蘇芳色", "Japanese", "#8d4052"),
            PredefinedColor("Dark Brown", "臙脂色", "Japanese", "#a11a3f"),
            PredefinedColor("Tokiro", "鴇色", "Japanese", "#f99fb0"),
            PredefinedColor("Sakura", "桜色", "Japanese", "#ffe1e1"),
            PredefinedColor("Kanzorio", "萱草色", "Japanese", "#f6a44f"),
            PredefinedColor("Shochu", "洗朱", "Japanese", "#dd6846"),
            PredefinedColor("Soba", "蘇比", "Japanese", "#eb7a55"),
            PredefinedColor("Amber", "琥珀色", "Japanese", "#b97b41"),
            PredefinedColor("Red Gold", "紅鬱金", "Japanese", "#da7b4a"),
            PredefinedColor("Fox", "狐色", "Japanese", "#c87639"),
            PredefinedColor("Garnet", "蒲色", "Japanese", "#ce4130"),
            PredefinedColor("Fading Color", "代赭色", "Japanese", "#bd5f41"),
            PredefinedColor("Kotan", "黄丹", "Japanese", "#f07251"),
            PredefinedColor("Road Tea", "路考茶", "Japanese", "#a56d32"),
            PredefinedColor("Red Pattern", "弁柄色", "Japanese", "#87392d"),
            PredefinedColor("Chara", "伽羅", "Japanese", "#da9467"),
            PredefinedColor("Kaba Tea", "蒲茶", "Japanese", "#726250"),
            PredefinedColor("Ebi-Chan", "海老茶", "Japanese", "#511d10"),
            PredefinedColor("Bamboo Soot", "煤竹色", "Japanese", "#58443c"),
            PredefinedColor("Yuzu Tea", "鶯茶", "Japanese", "#5b4c25"),
            PredefinedColor("Rikyu Tea", "利休茶", "Japanese", "#70643d"),
            PredefinedColor("Ai Tea", "藍海松茶", "Japanese", "#56564b"),
            PredefinedColor("Kitochi", "黄橡", "Japanese", "#977250"),
            PredefinedColor("Spicy Tea", "焦茶", "Japanese", "#3e2822"),
            PredefinedColor("White Tea", "白茶", "Japanese", "#dfbd9f"),
            PredefinedColor("Edo Tea", "江戸茶", "Japanese", "#a56c4f"),
            PredefinedColor("Zenza Tea", "千載茶", "Japanese", "#232827"),
            PredefinedColor("Danjuro Tea", "団十郎茶", "Japanese", "#975e45"),
            PredefinedColor("Riyashi Tea", "璃寛茶", "Japanese", "#6e6636"),
            PredefinedColor("Dust", "文人茶", "Japanese", "#56453e"),
            PredefinedColor("Gardenia", "支子色", "Japanese", "#f9c252"),
            PredefinedColor("Yamabuki", "山吹色", "Japanese", "#f6ae23"),
            PredefinedColor("Depression", "鬱金色", "Japanese", "#f8b817"),
            PredefinedColor("Ocher", "黄土色", "Japanese", "#c18c42"),
            PredefinedColor("Flax", "亜麻色", "Japanese", "#d6c6af"),
            PredefinedColor("Kariyasu", "刈安色", "Japanese", "#ecdb71"),
            PredefinedColor("Kihadairo", "黄蘗色", "Japanese", "#d8c639"),
            PredefinedColor("Baby Bird", "鳥の子色", "Japanese", "#ffeec0"),
            PredefinedColor("Egg", "玉子色", "Japanese", "#fcc37b"),
            PredefinedColor("Moss", "苔色", "Japanese", "#63822d"),
            PredefinedColor("Gray", "鶸色", "Japanese", "#b9cb36"),
            PredefinedColor("Carp", "萌黄", "Japanese", "#6ab540"),
            PredefinedColor("White Green", "白緑", "Japanese", "#b4dccb"),
            PredefinedColor("Pine Needle", "松葉色", "Japanese", "#939e6c"),
            PredefinedColor("Greenish Brown", "鶯色", "Japanese", "#83823d"),
            PredefinedColor("Blue Bamboo", "青竹色", "Japanese", "#7ebeab"),
            PredefinedColor("Maiko", "海松色", "Japanese", "#726d40"),
            PredefinedColor("Seedling", "苗色", "Japanese", "#92b07e"),
            PredefinedColor("Horsetail", "木賊色", "Japanese", "#3a8165"),
            PredefinedColor("Celadon", "青磁色", "Japanese", "#6ab59a"),
            PredefinedColor("Green Blue", "緑青色", "Japanese", "#2f7a64"),
            PredefinedColor("Mizuasagi", "水浅葱", "Japanese", "#93cbd7"),
            PredefinedColor("Ruriiro", "瑠璃色", "Japanese", "#344694"),
            PredefinedColor("Shimbashi", "新橋色", "Japanese", "#4cb6c2"),
            PredefinedColor("Gray", "縹色", "Japanese", "#425b90"),
            PredefinedColor("Asam", "浅葱色", "Japanese", "#00879d"),
            PredefinedColor("Flower Asan", "花浅葱", "Japanese", "#2a83a2"),
            PredefinedColor("Sky Blue", "空色", "Japanese", "#86cdee"),
            PredefinedColor("Ultramarine", "群青色", "Japanese", "#444c98"),
            PredefinedColor("Light Blue", "水色", "Japanese", "#afdfe4"),
            PredefinedColor("Cyan", "藍色", "Japanese", "#2b4b65"),
            PredefinedColor("Peeping", "甕覗", "Japanese", "#b3dedf"),
            PredefinedColor("Brown", "褐色", "Japanese", "#1e1835"),
            PredefinedColor("Navy", "紺色", "Japanese", "#394b72"),
            PredefinedColor("Iron", "鉄色", "Japanese", "#335145"),
            PredefinedColor("Navy Blue", "紺青色", "Japanese", "#1b2742"),
            PredefinedColor("Grass", "露草色", "Japanese", "#6aa5d6"),
            PredefinedColor("Rusting Pit", "錆御納戸", "Japanese", "#3d6562"),
            PredefinedColor("Indigo Rust", "藍錆色", "Japanese", "#393e7a"),
            PredefinedColor("Indian Iron", "藍鉄色", "Japanese", "#242e41"),
            PredefinedColor("Usuiro", "薄色", "Japanese", "#a08b94"),
            PredefinedColor("Violet", "菫色", "Japanese", "#75639e"),
            PredefinedColor("Kikyo", "桔梗色", "Japanese", "#574b96"),
            PredefinedColor("Edo Purple", "江戸紫", "Japanese", "#5b3970"),
            PredefinedColor("Ancient Purple", "古代紫", "Japanese", "#6e3c6d"),
            PredefinedColor("Kyoto Purple", "京紫", "Japanese", "#6f3762"),
            PredefinedColor("Pink Purple", "滅紫", "Japanese", "#442b3a"),
            PredefinedColor("Shioniro", "紫苑色", "Japanese", "#867ba9"),
            PredefinedColor("Wisteria", "藤色", "Japanese", "#c1c0db"),
            PredefinedColor("Two Indigo", "二藍", "Japanese", "#6b4978"),
            PredefinedColor("Bluish Purple", "紫紺", "Japanese", "#4a2a4c"),
            PredefinedColor("Rustic Bellflower", "錆桔梗", "Japanese", "#5d547f"),
            PredefinedColor("Green Plum", "梅鼠", "Japanese", "#c099a0"),
            PredefinedColor("Silver Mouse", "銀鼠", "Japanese", "#afafb0"),
            PredefinedColor("Lime", "灰汁色", "Japanese", "#958970"),
            PredefinedColor("Ridiculous Rat", "利休鼠", "Japanese", "#888e7e"),
            PredefinedColor("Hatobairo", "鳩羽色", "Japanese", "#a69aad"),
            PredefinedColor("Ainuzu", "藍鼠", "Japanese", "#6c848d"),
            PredefinedColor("Fukugawa Rat", "深川鼠", "Japanese", "#97a791"),
            PredefinedColor("Blue Blossom", "青鈍", "Japanese", "#6e7b71"),
            PredefinedColor("Grape Rice", "葡萄", "Japanese", "#705b67"),
            
            //FS-595
            PredefinedColor("Brown Special", "FS-595", "#532F15"),
            PredefinedColor("Insignia Red", "FS-595", "#9B2F25"),
            PredefinedColor("Pink", "FS-595", "#ECB2A6"),
            PredefinedColor("International Orange", "FS-595", "#BA160C"),
            PredefinedColor("Orange Yellow", "FS-595", "#F5AB30"),
            PredefinedColor("Yellow", "FS-595", "#F7D100"),
            PredefinedColor("Blue Angels Yellow", "FS-595", "#FDD31D"),
            PredefinedColor("Lime Yellow", "FS-595", "#DBE568"),
            PredefinedColor("Green", "FS-595", "#373D2F"),
            PredefinedColor("Dark Green", "FS-595", "#3C341F"),
            PredefinedColor("Green", "FS-595", "#006845"),
            PredefinedColor("Green", "FS-595", "#515E32"),
            PredefinedColor("Sea Blue", "FS-595", "#070D09"),
            PredefinedColor("Insignia Blue", "FS-595", "#2A3141"),
            PredefinedColor("Blue", "FS-595", "#001068"),
            PredefinedColor("Dark Blue", "FS-595", "#023457"),
            PredefinedColor("Bright Blue", "FS-595", "#0E5A8B"),
            PredefinedColor("Sky Blue", "FS-595", "#7CBCE0"),
            PredefinedColor("Air Superiority Blue", "FS-595", "#72A0C1"),
            PredefinedColor("Engine Gray", "FS-595", "#353736"),
            PredefinedColor("Engine Gray", "FS-595", "#3B3F42"),
            PredefinedColor("Light Gull Gray", "FS-595", "#8A8685"),
            PredefinedColor("Aircraft Gray", "FS-595", "#9EA2A3"),
            PredefinedColor("Canadian Voodoo Gray", "FS-595", "#B8B7A3"),
            PredefinedColor("Black", "FS-595", "#03120F"),
            PredefinedColor("Purple", "FS-595", "#784a7a"),
            PredefinedColor("Insignia White", "FS-595", "#EDF2F8"),
            PredefinedColor("Insignia White", "FS-595", "#F8F9F3"),
            PredefinedColor("Fluorescent Red Orange", "FS-595", "#FC4827"),
            PredefinedColor("Maroon", "FS-595", "#531F23"),
            PredefinedColor("Brown", "FS-595", "#4A3733"),
            PredefinedColor("Brown Yellow", "FS-595", "#93400A"),
            PredefinedColor("Red Brown", "FS-595", "#83321F"),
            PredefinedColor("Brown Special", "FS-595", "#694024"),
            PredefinedColor("Tan", "FS-595", "#BC7756"),
            PredefinedColor("Tan", "FS-595", "#AF8D50"),
            PredefinedColor("Yellow Sand", "FS-595", "#A28744"),
            PredefinedColor("Tan", "FS-595", "#B9845C"),
            PredefinedColor("Night Tan", "FS-595", "#AB967B"),
            PredefinedColor("Tan", "FS-595", "#B9845C"),
            PredefinedColor("Red", "FS-595", "#B51F11"),
            PredefinedColor("Red", "FS-595", "#E43301"),
            PredefinedColor("Red", "FS-595", "#E94400"),
            PredefinedColor("Red", "FS-595", "#E43301"),
            PredefinedColor("Tan", "FS-595", "#E09F69"),
            PredefinedColor("Earth Yellow", "FS-595", "#CE981A"),
            PredefinedColor("Cream", "FS-595", "#DBCCA5"),
            PredefinedColor("Beige", "FS-595", "#DEC26E"),
            PredefinedColor("Yellow", "FS-595", "#FCCE16"),
            PredefinedColor("Sand", "FS-595", "#EEDDAF"),
            PredefinedColor("Yellow Sand", "FS-595", "#FACC7F"),
            PredefinedColor("Green", "FS-595", "#373D2F"),
            PredefinedColor("Forest Green", "FS-595", "#41402C"),
            PredefinedColor("Green", "FS-595", "#4EA04E"),
            PredefinedColor("Green", "FS-595", "#6D9477"),
            PredefinedColor("Green", "FS-595", "#91A395"),
            PredefinedColor("Blue", "FS-595", "#2758B5"),
            PredefinedColor("Blue", "FS-595", "#96ABAC"),
            PredefinedColor("Light Blue", "FS-595", "#CFD8DD"),
            PredefinedColor("Dark Gray", "FS-595", "#343A48"),
            PredefinedColor("Gray", "FS-595", "#172339"),
            PredefinedColor("Seaplane Gray", "FS-595", "#3B3F42"),
            PredefinedColor("Medium Gunship Gray", "FS-595", "#3F4952"),
            PredefinedColor("Gray", "FS-595", "#6A737A"),
            PredefinedColor("Medium Gray", "FS-595", "#797F7F"),
            PredefinedColor("Dark Compass Ghost Gray", "FS-595", "#808C8C"),
            PredefinedColor("Light Campers Ghost Gray", "FS-595", "#9598A1"),
            PredefinedColor("Light Gull Gray", "FS-595", "#878684"),
            PredefinedColor("Black", "FS-595", "#051111"),
            PredefinedColor("White", "FS-595", "#Fbfeeb"),
            PredefinedColor("Flourescent Red Orange", "FS-595", "#Fe4728"),
            PredefinedColor("Flourescent Red", "FS-595", "#Fb2b11"),
            PredefinedColor("Brown", "FS-595", "#543b34"),
            PredefinedColor("Leather Brown", "FS-595", "#443724"),
            PredefinedColor("Hull Red", "FS-595", "#4d140b"),
            PredefinedColor("Red Brown", "FS-595", "#612f24"),
            PredefinedColor("Brown", "FS-595", "#564032"),
            PredefinedColor("Brown", "FS-595", "#473622"),
            PredefinedColor("Red Brown", "FS-595", "#3C1E16"),
            PredefinedColor("Brown", "FS-595", "#4C2A21"),
            PredefinedColor("Earth Red", "FS-595", "#704437"),
            PredefinedColor("Field Drab", "FS-595", "#5B462B"),
            PredefinedColor("Brown Special", "FS-595", "#532f17"),
            PredefinedColor("Brown", "FS-595", "#6b433b"),
            PredefinedColor("Brown", "FS-595", "#70472b"),
            PredefinedColor("Tan", "FS-595", "#715540"),
            PredefinedColor("Tan", "FS-595", "#8d7a69"),
            PredefinedColor("Tan", "FS-595", "#B48e5d"),
            PredefinedColor("Yellow Sand", "FS-595", "#A28744"),
            PredefinedColor("Sand Brown", "FS-595", "#948b6c"),
            PredefinedColor("Sand", "FS-595", "#A58e7e"),
            PredefinedColor("Sand", "FS-595", "#B2a68c"),
            PredefinedColor("Yellow Sand", "FS-595", "#B58159"),
            PredefinedColor("Brown", "FS-595", "#694223"),
            PredefinedColor("Insignia Red", "FS-595", "#9a2e24"),
            PredefinedColor("Red", "FS-595", "#D32200"),
            PredefinedColor("Red", "FS-595", "#C41d0a"),
            PredefinedColor("Red", "FS-595", "#E94400"),
            PredefinedColor("Sand", "FS-595", "#E2c293"),
            PredefinedColor("Orange", "FS-595", "#Ef6c00"),
            PredefinedColor("Brown", "FS-595", "#5d4b33"),
            PredefinedColor("Tan", "FS-595", "#8f693a"),
            PredefinedColor("Sand", "FS-595", "#957f56"),
            PredefinedColor("Ochre", "FS-595", "#Bd8846"),
            PredefinedColor("Tan", "FS-595", "#9f9059"),
            PredefinedColor("Dessert Tan", "FS-595", "#A38c6c"),
            PredefinedColor("Dark Yellow", "FS-595", "#A59727"),
            PredefinedColor("MiddleStone", "FS-595", "#C7ab84"),
            PredefinedColor("Orange Yellow", "FS-595", "#Fec110"),
            PredefinedColor("Radome Tan", "FS-595", "#F1c7a1"),
            PredefinedColor("Sand", "FS-595", "#C6b490"),
            PredefinedColor("Sand", "FS-595", "#E3cfb7"),
            PredefinedColor("Yellow Sand", "FS-595", "#F5ca86"),
            PredefinedColor("Sand", "FS-595", "#Dfcba8"),
            PredefinedColor("Sand", "FS-595", "#F0d6b1"),
            PredefinedColor("Dark Green", "FS-595", "#2a2c1f"),
            PredefinedColor("USMC Green", "FS-595", "#373d31"),
            PredefinedColor("Sea Blue", "FS-595", "#46696f"),
            PredefinedColor("Dark Green", "FS-595", "#373828"),
            PredefinedColor("Green", "FS-595", "#344034"),
            PredefinedColor("Forest Green", "FS-595", "#423f2c"),
            PredefinedColor("Green", "FS-595", "#44503a"),
            PredefinedColor("Green", "FS-595", "#3a4630"),
            PredefinedColor("Green", "FS-595", "#282a1d"),
            PredefinedColor("I.R. Dark Green", "FS-595", "#404034"),
            PredefinedColor("Olive Drab", "FS-595", "#3c3421"),
            PredefinedColor("Olive Drab", "FS-595", "#3c341f"),
            PredefinedColor("Dark Green", "FS-595", "#364a41"),
            PredefinedColor("Green", "FS-595", "#3e3d29"),
            PredefinedColor("Field Green", "FS-595", "#3b482c"),
            PredefinedColor("Dark Green", "FS-595", "#454d42"),
            PredefinedColor("Field Green", "FS-595", "#4a4c34"),
            PredefinedColor("Green", "FS-595", "#4f5338"),
            PredefinedColor("Light Green", "FS-595", "#454932"),
            PredefinedColor("Medium Green", "FS-595", "#1b4b21"),
            PredefinedColor("Green", "FS-595", "#455238"),
            PredefinedColor("Deep Green", "FS-595", "#4b654a"),
            PredefinedColor("Green", "FS-595", "#19481e"),
            PredefinedColor("Interior Green", "FS-595", "#536537"),
            PredefinedColor("Green", "FS-595", "#585e50"),
            PredefinedColor("Tan Green", "FS-595", "#685d47"),
            PredefinedColor("Medium Gray Green", "FS-595", "#4d6b53"),
            PredefinedColor("Green", "FS-595", "#2f6031"),
            PredefinedColor("Green", "FS-595", "#6f8054"),
            PredefinedColor("Yellow Green", "FS-595", "#51680e"),
            PredefinedColor("Green", "FS-595", "#A8b693"),
            PredefinedColor("Light Gray Green", "FS-595", "#9fad8c"),
            PredefinedColor("Light Gray Green", "FS-595", "#A0b29a"),
            PredefinedColor("Light Green", "FS-595", "#C4da99"),
            PredefinedColor("Sky", "FS-595", "#C7c9a4"),
            PredefinedColor("Green", "FS-595", "#D8efab"),
            PredefinedColor("Sea Blue", "FS-595", "#151b17"),
            PredefinedColor("Insignia Blue", "FS-595", "#323c48"),
            PredefinedColor("Dark Blue", "FS-595", "#355061"),
            PredefinedColor("Blue", "FS-595", "#263a75"),
            PredefinedColor("Dark Blue", "FS-595", "#273d55"),
            PredefinedColor("Intermediate Blue", "FS-595", "#56626e"),
            PredefinedColor("Medium Blue", "FS-595", "#436f94"),
            PredefinedColor("Blue Gray", "FS-595", "#687681"),
            PredefinedColor("Dark Blue", "FS-595", "#6a85a2"),
            PredefinedColor("Azure Blue", "FS-595", "#757fa3"),
            PredefinedColor("Gray Blue", "FS-595", "#67757e"),
            PredefinedColor("Blue", "FS-595", "#7882a5"),
            PredefinedColor("Blue", "FS-595", "#3592bd"),
            PredefinedColor("Blue", "FS-595", "#8fabae"),
            PredefinedColor("Blue", "FS-595", "#789b9d"),
            PredefinedColor("Air Superiority Blue", "FS-595", "#7499ac"),
            PredefinedColor("Light Sky Blue", "FS-595", "#9db4c6"),
            PredefinedColor("Light Blue", "FS-595", "#C9d5d1"),
            PredefinedColor("Gray", "FS-595", "#3b3e51"),
            PredefinedColor("Dark Gunship Gray", "FS-595", "#3b3f42"),
            PredefinedColor("Dark Gray", "FS-595", "#474d49"),
            PredefinedColor("Medium Gunship Gray", "FS-595", "#414a53"),
            PredefinedColor("Gray", "FS-595", "#545e56"),
            PredefinedColor("Gray", "FS-595", "#7a755f"),
            PredefinedColor("Neutral Gray", "FS-595", "#606666"),
            PredefinedColor("Dark Gull Gray", "FS-595", "#40474d"),
            PredefinedColor("Dark Gull Gray", "FS-595", "#6f7571"),
            PredefinedColor("Gray", "FS-595", "#6a6c6b"),
            PredefinedColor("Medium Gray", "FS-595", "#7a7f82"),
            PredefinedColor("Dark Gray", "FS-595", "#7f8581"),
            PredefinedColor("Aircraft Exterior Gray", "FS-595", "#939498"),
            PredefinedColor("Gray", "FS-595", "#95928d"),
            PredefinedColor("Flint Gray", "FS-595", "#8b8c84"),
            PredefinedColor("Dark Compass Ghost Gray", "FS-595", "#818b8d"),
            PredefinedColor("Light Gray", "FS-595", "#819490"),
            PredefinedColor("Light Gray", "FS-595", "#8a8e8d"),
            PredefinedColor("Light Compass Ghost Gray", "FS-595", "#9598a1"),
            PredefinedColor("Medium Gray", "FS-595", "#BAB2A5"),
            PredefinedColor("Gray", "FS-595", "#A7b6b9"),
            PredefinedColor("Light Gull Gray", "FS-595", "#Acaca4"),
            PredefinedColor("Sky Gray", "FS-595", "#98a6a7"),
            PredefinedColor("Gray", "FS-595", "#B7b4ab"),
            PredefinedColor("Light Gray", "FS-595", "#C6c5ca"),
            PredefinedColor("Tan", "FS-595", "#B9b19c"),
            PredefinedColor("Tan", "FS-595", "#A3947d"),
            PredefinedColor("Gray", "FS-595", "#Bfbbb2"),
            PredefinedColor("Gray", "FS-595", "#C8c1b1"),
            PredefinedColor("Black Gray", "FS-595", "#24272e"),
            PredefinedColor("Black", "FS-595", "#051111"),
            PredefinedColor("Purple", "FS-595", "#794b7a"),
            PredefinedColor("White", "FS-595", "#Fdfbd2"),
            //JNR colors.
            PredefinedColor("Red", "赤1号", "JNR", "#b2152b"),
            PredefinedColor("Red", "赤2号", "JNR", "#842B32"),
            PredefinedColor("Red Brown", "赤3号", "JNR", "#7A453D"),
            PredefinedColor("Maroon", "赤7号", "JNR", "#563533"),
            PredefinedColor("Scarlet", "赤11号", "JNR", "#C32829"),
            PredefinedColor("Light Bean Color", "赤13号", "JNR", "#88474B"),
            PredefinedColor("Red 14", "赤14号", "JNR", "#C9242F"),
            PredefinedColor("Grape Color 1", "ぶどう色1号", "JNR", "#35271D"),
            PredefinedColor("Grape Color 2", "ぶどう色2号", "JNR", "#413027"),
            PredefinedColor("Grape Color 3", "ぶどう色3号", "JNR", "#58211C"),
            PredefinedColor("Faint", "とび色2号", "JNR", "#735340"),
            PredefinedColor("Orange Vermilion", "朱色1号", "JNR", "#C16543"),
            PredefinedColor("Vermilion", "朱色3号", "JNR", "#E03625"),
            PredefinedColor("Gold Red", "朱色4号", "JNR", "#B53D27"),
            PredefinedColor("Persimmon", "朱色5号", "JNR", "#CA4F3C"),
            PredefinedColor("Yellow", "黄1号", "JNR", "#FDBC00"),
            PredefinedColor("Light Yellow", "黄4号", "JNR", "#EACD6F"),
            PredefinedColor("Marigold", "黄5号", "JNR", "#E3B144"),
            PredefinedColor("Light Egg", "黄6号", "JNR", "#F7E19E"),
            PredefinedColor("Cream 1", "クリーム1号", "JNR", "#D6BC96"),
            PredefinedColor("Cream 2", "クリーム2号", "JNR", "#E0C37B"),
            PredefinedColor("Cream 3", "クリーム3号", "JNR", "#E2A665"),
            PredefinedColor("Cream 4", "クリーム4号", "JNR", "#CFAC84"),
            PredefinedColor("Cream 9", "クリーム9号", "JNR", "#CABEAC"),
            PredefinedColor("Cream 10", "クリーム10号", "JNR", "#ECE0D1"),
            PredefinedColor("Cream 12", "クリーム12号", "JNR", "#E6E1D5"),
            PredefinedColor("Mandarin Orange", "黄かん色", "JNR", "#CA6A1F"),
            PredefinedColor("Yellowish-Brown 1", "黄かっ色1号", "JNR", "#A57C4A"),
            PredefinedColor("Yellowish-Brown 2", "黄かっ色2号", "JNR", "#988054"),
            PredefinedColor("Light Green 1", "淡緑1号", "JNR", "#9EAE9C"),
            PredefinedColor("Mist Green", "淡緑3号", "JNR", "#7B9681"),
            PredefinedColor("Light Green 5", "淡緑5号", "JNR", "#546C55"),
            PredefinedColor("Light Green 6", "淡緑6号", "JNR", "#97BC94"),
            PredefinedColor("Silver Green", "淡緑7号", "JNR", "#BAB8A9"),
            PredefinedColor("Moe", "黄緑6号", "JNR", "#7BAB4F"),
            PredefinedColor("Yellowish-Green", "黄緑7号", "JNR", "#57B544"),
            PredefinedColor("Green 1", "緑1号", "JNR", "#005E54"),
            PredefinedColor("Dark Green", "緑2号", "JNR", "#354F33"),
            PredefinedColor("Moss Green", "緑14号", "JNR", "#246029"),
            PredefinedColor("Green 15", "緑15号", "JNR", "#2E8B57"),
            PredefinedColor("Grayish-Green", "灰緑色2号", "JNR", "#6D8881"),
            PredefinedColor("Slate Green", "灰緑色3号", "JNR", "#3B6063"),
            PredefinedColor("Emerald Green", "青緑1号", "JNR", "#009786"),
            PredefinedColor("Iron", "青緑6号", "JNR", "#003835"),
            PredefinedColor("Blue 1", "青1号", "JNR", "#417A83"),
            PredefinedColor("Ultramarine", "青2号", "JNR", "#324C51"),
            PredefinedColor("Blue 3", "青3号", "JNR", "#2A3444"),
            PredefinedColor("Sky Blue", "青9号", "JNR", "#52799E"),
            PredefinedColor("Ink Blue", "青15号", "JNR", "#234059"),
            PredefinedColor("Slate Blue", "青19号", "JNR", "#496779"),
            PredefinedColor("Bright Blue", "青20号", "JNR", "#003F6C"),
            PredefinedColor("Water", "青22号", "JNR", "#00859E"),
            PredefinedColor("Blue 23", "青23号", "JNR", "#004F8A"),
            PredefinedColor("Blue 24", "青24号", "JNR", "#00B2E5"),
            PredefinedColor("Blue 26", "青26号", "JNR", "#00acd1"),
            PredefinedColor("Sand Beige", "薄茶色4号", "JNR", "#B4A18E"),
            PredefinedColor("Flesh", "薄茶色5号", "JNR", "#D99574"),
            PredefinedColor("Tea Mouse", "薄茶色6号", "JNR", "#AEA29B"),
            PredefinedColor("Light Brown", "薄茶色13号", "JNR", "#D1C3B5"),
            PredefinedColor("White Brown", "薄茶色14号", "JNR", "#DDD2C5"),
            PredefinedColor("Cocoa Brown", "薄茶色15号", "JNR", "#765F4B"),
            PredefinedColor("Beige", "薄茶色17号", "JNR", "#A98A68"),
            PredefinedColor("Black", "黒", "JNR", "#2a2a2a"),
            PredefinedColor("Mouse", "ねずみ色1号", "JNR", "#767676"),
            PredefinedColor("Gray", "灰色1号", "JNR", "#8f8f8f"),
            PredefinedColor("Silver Gray", "灰色8号", "JNR", "#aaaaaa"),
            PredefinedColor("Pearl White", "灰色9号", "JNR", "#c5c5c5"),
            PredefinedColor("Frosty White", "灰色16号", "JNR", "#d3d3d3"),
            PredefinedColor("White 3", "白3号", "JNR", "#e7e7e8"),
            //iOS colors.
            PredefinedColor("Black", "iOS", UIColor.black),
            PredefinedColor("Blue", "iOS", UIColor.blue),
            PredefinedColor("Brown", "iOS", UIColor.brown),
            PredefinedColor("Cyan", "iOS", UIColor.cyan),
            PredefinedColor("Dark Gray", "iOS", UIColor.darkGray),
            PredefinedColor("Gray", "iOS", UIColor.gray),
            PredefinedColor("Green", "iOS", UIColor.green),
            PredefinedColor("Light Gray", "iOS", UIColor.lightGray),
            PredefinedColor("Magenta", "iOS", UIColor.magenta),
            PredefinedColor("Orange", "iOS", UIColor.orange),
            PredefinedColor("Purple", "iOS", UIColor.purple),
            PredefinedColor("Red", "iOS", UIColor.red),
            PredefinedColor("White", "iOS", UIColor.white),
            PredefinedColor("Yellow", "iOS", UIColor.yellow),
            //X11 colors.
            PredefinedColor("Alice Blue", "X11", "#f0f8ff"),
            PredefinedColor("Antique White", "X11", "#faebd7"),
            PredefinedColor("Aqua", "X11", "#00ffff"),
            PredefinedColor("Aquamarine", "X11", "#7fffd4"),
            PredefinedColor("Azure", "X11", "#f0ffff"),
            PredefinedColor("Beige", "X11", "#f5f5dc"),
            PredefinedColor("Bisque", "X11", "#ffe4c4"),
            PredefinedColor("Black", "X11", "#000000"),
            PredefinedColor("Blanched Almond", "X11", "#ffebcd"),
            PredefinedColor("Blue", "X11", "#0000ff"),
            PredefinedColor("Blue Violet", "X11", "#8a2be2"),
            PredefinedColor("Brown", "X11", "#a52a2a"),
            PredefinedColor("Burlywood", "X11", "#deb887"),
            PredefinedColor("Cadet Blue", "X11", "#5f9ea0"),
            PredefinedColor("Chartreuse", "X11", "#7fff00"),
            PredefinedColor("Chocolate", "X11", "#d2691e"),
            PredefinedColor("Coral", "X11", "#ff7f50"),
            PredefinedColor("Cornflower", "X11", "#6495ed"),
            PredefinedColor("Cornsilk", "X11", "#fff8dc"),
            PredefinedColor("Crimson", "X11", "#dc143c"),
            PredefinedColor("Cyan", "X11", "#00ffff"),
            PredefinedColor("Dark Blue", "X11", "#00008b"),
            PredefinedColor("Dark Cyan", "X11", "#008b8b"),
            PredefinedColor("Dark Goldenrod", "X11", "#b8860b"),
            PredefinedColor("Dark Gray", "X11", "#a9a9a9"),
            PredefinedColor("Dark Green", "X11", "#006400"),
            PredefinedColor("Dark Khaki", "X11", "#bdb76b"),
            PredefinedColor("Dark Magenta", "X11", "#8b00b8"),
            PredefinedColor("Dark Olive Green", "X11", "#556b2f"),
            PredefinedColor("Dark Orange", "X11", "#ff8c00"),
            PredefinedColor("Dark Orchid", "X11", "#9932cc"),
            PredefinedColor("Dark Red", "X11", "#8b0000"),
            PredefinedColor("Dark Salmon", "X11", "#e9967a"),
            PredefinedColor("Dark Sea Green", "X11", "#8fbc8f"),
            PredefinedColor("Dark Slate Blue", "X11", "#483d8b"),
            PredefinedColor("Dark Slate Gray", "X11", "#2f4f4f"),
            PredefinedColor("Dark Turquoise", "X11", "#00ced1"),
            PredefinedColor("Dark Violet", "X11", "#9400d3"),
            PredefinedColor("Deep Pink", "X11", "#ff1493"),
            PredefinedColor("Deep Sky Blue", "X11", "#00bfff"),
            PredefinedColor("Dim Gray", "X11", "#696969"),
            PredefinedColor("Dodger Blue", "X11", "#1e90ff"),
            PredefinedColor("Firebrick", "X11", "#b22222"),
            PredefinedColor("Floral White", "X11", "#fffaf0"),
            PredefinedColor("Forest Green", "X11", "#228b22"),
            PredefinedColor("Fuchsia", "X11", "#ff00ff"),
            PredefinedColor("Gainsboro", "X11", "#dcdcdc"),
            PredefinedColor("Ghost White", "X11", "#f8f8ff"),
            PredefinedColor("Gold", "X11", "#ffd700"),
            PredefinedColor("Goldenrod", "X11", "#daa520"),
            PredefinedColor("Gray", "X11", "#bebebe"),
            PredefinedColor("Web Gray", "X11", "#808080"),
            PredefinedColor("Green", "X11", "#00ff00"),
            PredefinedColor("Web Green", "X11", "#008000"),
            PredefinedColor("Green Yellow", "X11", "#adff2f"),
            PredefinedColor("Honeydew", "X11", "#f0fff0"),
            PredefinedColor("Hot Pink", "X11", "#ff69b4"),
            PredefinedColor("Indian Red", "X11", "#cd5d5d"),
            PredefinedColor("Indigo", "X11", "#4b0082"),
            PredefinedColor("Ivory", "X11", "#fffff0"),
            PredefinedColor("Khaki", "X11", "#f0e68c"),
            PredefinedColor("Lavender", "X11", "#e6e6fa"),
            PredefinedColor("Lavender Blush", "X11", "#fff0f5"),
            PredefinedColor("Lawn Green", "X11", "#7cfc00"),
            PredefinedColor("Lemon Chiffon", "X11", "#fffacd"),
            PredefinedColor("Light Blue", "X11", "#add8e6"),
            PredefinedColor("Light Coral", "X11", "#f08080"),
            PredefinedColor("Light Cyan", "X11", "#e0ffff"),
            PredefinedColor("Light Goldenrod", "X11", "#fafad2"),
            PredefinedColor("Light Gray", "X11", "#d3d3d3"),
            PredefinedColor("Light Green", "X11", "#90ee90"),
            PredefinedColor("Light Pink", "X11", "#ffb6c1"),
            PredefinedColor("Light Salmon", "X11", "#ffa07a"),
            PredefinedColor("Light Sea Green", "X11", "#20b2aa"),
            PredefinedColor("Light Sky Blue", "X11", "#87cefa"),
            PredefinedColor("Light Slate Gray", "X11", "#778899"),
            PredefinedColor("Light Steel Blue", "X11", "#b0c4de"),
            PredefinedColor("Light Yellow", "X11", "#ffffe0"),
            PredefinedColor("Lime", "X11", "#00ff00"),
            PredefinedColor("Lime Green", "X11", "#32cd32"),
            PredefinedColor("Linen", "X11", "#faf0e6"),
            PredefinedColor("Magenta", "X11", "#ff00ff"),
            PredefinedColor("Maroon", "X11", "#b03060"),
            PredefinedColor("Web Maroon", "X11", "#7f0000"),
            PredefinedColor("Medium Aquamarine", "X11", "#66cdaa"),
            PredefinedColor("Medium Blue", "X11", "#0000cd"),
            PredefinedColor("Medium Purple", "X11", "#9370db"),
            PredefinedColor("Medium Sea Green", "X11", "#3cb371"),
            PredefinedColor("Medium Slate Blue", "X11", "#7b68ee"),
            PredefinedColor("Medium Spring Green", "X11", "#00fa9a"),
            PredefinedColor("Meidum Turquioise", "X11", "#48d1cc"),
            PredefinedColor("Medium Violet Red", "X11", "#c71585"),
            PredefinedColor("Midnight Blue", "X11", "#191970"),
            PredefinedColor("Mint Cream", "X11", "#f5fffa"),
            PredefinedColor("Misty Rose", "X11", "#ffe4e1"),
            PredefinedColor("Moccasin", "X11", "#ffe4b5"),
            PredefinedColor("Navajo White", "X11", "#ffdead"),
            PredefinedColor("Navy Blue", "X11", "#000080"),
            PredefinedColor("Old Lace", "X11", "#fdf5e6"),
            PredefinedColor("Olive", "X11", "#808000"),
            PredefinedColor("Olive Drab", "X11", "#6b8e23"),
            PredefinedColor("Orange", "X11", "#ffa500"),
            PredefinedColor("Orange Red", "X11", "#ff4500"),
            PredefinedColor("Orchid", "X11", "#da70d6"),
            PredefinedColor("Pale Goldenrod", "X11", "#eee8aa"),
            PredefinedColor("Pale Green", "X11", "#98fb98"),
            PredefinedColor("Pale Turquoise", "X11", "#afeeee"),
            PredefinedColor("Pale Violet Red", "X11", "#db7093"),
            PredefinedColor("Papaya Whip", "X11", "#ffefd5"),
            PredefinedColor("Peach Puff", "X11", "#ffdab9"),
            PredefinedColor("Peru", "X11", "#cd853f"),
            PredefinedColor("Pink", "X11", "#ffc0cb"),
            PredefinedColor("Plum", "X11", "#dda0dd"),
            PredefinedColor("Powder Blue", "X11", "#b0e0e6"),
            PredefinedColor("Purple", "X11", "#a020f0"),
            PredefinedColor("Web Purple", "X11", "#7f007f"),
            PredefinedColor("Rebecca Purple", "X11", "#663399"),
            PredefinedColor("Red", "X11", "#ff0000"),
            PredefinedColor("Rosy Brown", "X11", "#bc8f8f"),
            PredefinedColor("Royal Blue", "X11", "#4169e1"),
            PredefinedColor("Saddle Brown", "X11", "#8b4513"),
            PredefinedColor("Salmon", "X11", "#fa8072"),
            PredefinedColor("Sandy Brown", "X11", "#f4a460"),
            PredefinedColor("Sea Green", "X11", "#2e8b57"),
            PredefinedColor("Seashell", "X11", "#fff5ee"),
            PredefinedColor("Sienna", "X11", "#a0522d"),
            PredefinedColor("Silver", "X11", "#c0c0c0"),
            PredefinedColor("Sky Blue", "X11", "#87ceeb"),
            PredefinedColor("Slate Blue", "X11", "#6a5acd"),
            PredefinedColor("Slate Gray", "X11", "#708090"),
            PredefinedColor("Snow", "X11", "#fffafa"),
            PredefinedColor("Spring Green", "X11", "#00ff7f"),
            PredefinedColor("Steel Blue", "X11", "#4682b4"),
            PredefinedColor("Tan", "X11", "#d2b48c"),
            PredefinedColor("Thistle", "X11", "#d8bfd8"),
            PredefinedColor("Tomato", "X11", "#ff6347"),
            PredefinedColor("Turquoise", "X11", "#40e0d0"),
            PredefinedColor("Violet", "X11", "#ee82ee"),
            PredefinedColor("Wheat", "X11", "#f5deb3"),
            PredefinedColor("White", "X11", "#ffffff"),
            PredefinedColor("White Smoke", "X11", "#f5f5f5"),
            PredefinedColor("Yellow", "X11", "#ffff00"),
            PredefinedColor("Yellow Green", "X11", "#9acd32"),
            // Pastel colors
            PredefinedColor("Atomic Tangerine", "Pastel", "#ff9966"),
            PredefinedColor("Baby Blue", "Pastel", "#89cff0"),
            PredefinedColor("Blizzard Blue", "Pastel", "#ace5ee"),
            PredefinedColor("BluePastel", "Pastel", "#b2cefe"),
            PredefinedColor("Brilliant Lavender", "Pastel", "#f4bbff"),
            PredefinedColor("Champagne", "Pastel", "#f7e7ce"),
            PredefinedColor("Chartreuse", "Pastel", "#dfff00"),
            PredefinedColor("Citrine", "Pastel", "#e4d00a"),
            PredefinedColor("Coral", "Pastel", "#ff7e50"),
            PredefinedColor("Cotton Candy", "Pastel", "#ffbcd9"),
            PredefinedColor("Daffodil", "Pastel", "#ffff31"),
            PredefinedColor("Dark Pastel Green", "Pastel", "#03c03c"),
            PredefinedColor("Dark Sea Green", "Pastel", "#8fbc8f"),
            PredefinedColor("Deep Sky Blue", "Pastel", "#00bfff"),
            PredefinedColor("Electric Lime", "Pastel", "#ccff00"),
            PredefinedColor("Flavescent", "Pastel", "#f7e98e"),
            PredefinedColor("Floral White", "Pastel", "#fffaf0"),
            PredefinedColor("Gold", "Pastel", "#ffd700"),
            PredefinedColor("Granny Smith", "Pastel", "#a8e4a0"),
            PredefinedColor("Green Pastel", "Pastel", "#baed91"),
            PredefinedColor("Honey Dew", "Pastel", "#f0fff0"),
            PredefinedColor("Lavender", "Pastel", "#e6e6fa"),
            PredefinedColor("Light Blue", "Pastel", "#add8e6"),
            PredefinedColor("Light Goldenrod Yellow", "Pastel", "#fafad2"),
            PredefinedColor("Linen", "Pastel", "#faf0e6"),
            PredefinedColor("Magic Mint", "Pastel", "#aaf0d1"),
            PredefinedColor("Mauve", "Pastel", "#b784a7"),
            PredefinedColor("Mint Cream", "Pastel", "#f5fffa"),
            PredefinedColor("Misty Rose", "Pastel", "#ffe4e1"),
            PredefinedColor("Moccasin", "Pastel", "#ffe4b5"),
            PredefinedColor("Mustard", "Pastel", "#ffdb58"),
            PredefinedColor("Old Lace", "Pastel", "#fdf5e6"),
            PredefinedColor("Orange Pastel", "Pastel", "#f8b88b"),
            PredefinedColor("Pale Cerulean", "Pastel", "#9bc4e2"),
            PredefinedColor("Pale Goldenrod", "Pastel", "#eee8aa"),
            PredefinedColor("Pale Gray", "Pastel", "#f0f0f0"),
            PredefinedColor("Pale Pink", "Pastel", "#fadadd"),
            PredefinedColor("Papaya Whip", "Pastel", "#ffefd5"),
            PredefinedColor("Pastel Brown", "Pastel", "#836953"),
            PredefinedColor("Pastel Magenta", "Pastel", "#f49ac2"),
            PredefinedColor("Pastel Pink", "Pastel", "#ffd1dc"),
            PredefinedColor("Pastel Purple", "Pastel", "#b39eb5"),
            PredefinedColor("Pastel Red", "Pastel", "#ff6961"),
            PredefinedColor("Pastel Yellow", "Pastel", "#fdfd96"),
            PredefinedColor("Peach Puff", "Pastel", "#ffdab9"),
            PredefinedColor("Periwinkle", "Pastel", "#ccccff"),
            PredefinedColor("Pink", "Pastel", "#ffc0cb"),
            PredefinedColor("Pink Pastel", "Pastel", "#fea3aa"),
            PredefinedColor("Pistachio", "Pastel", "#93c572"),
            PredefinedColor("Platinum", "Pastel", "#e5e4e2"),
            PredefinedColor("Purple Pastel", "Pastel", "#f2a2eb"),
            PredefinedColor("Saffron", "Pastel", "#f4c430"),
            PredefinedColor("Sandstorm", "Pastel", "#ecd540"),
            PredefinedColor("Seashell", "Pastel", "#fff5ee"),
            PredefinedColor("Sun Glow", "Pastel", "#ffcc33"),
            PredefinedColor("Sunset", "Pastel", "#fad6a5"),
            PredefinedColor("Tea Rose", "Pastel", "#f4c2c2"),
            PredefinedColor("Thistle", "Pastel", "#d8bfd8"),
            PredefinedColor("Tomato", "Pastel", "#ff6347"),
            PredefinedColor("Vivid Tangerine", "Pastel", "#ffa089"),
            PredefinedColor("Wild Blue Yonder", "Pastel", "#a2add0"),
            PredefinedColor("Yellow Pastel", "Pastel", "#faf884"),
            PredefinedColor("Yellow Process", "Pastel", "#ffef00"),
    ]
}
